/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cocktail.ui;

import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author visaac
 */
public class AdaptationSettingsDialog extends javax.swing.JDialog {

    /**
     * Creates new form AdaptationSettingsDiaog
     */
    public AdaptationSettingsDialog(java.awt.Frame parent) {
        super(parent, true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblStageTitle = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        butCurrentReset = new javax.swing.JButton();
        butCurrentAction = new javax.swing.JButton();
        jcbSupplementaryJuice = new javax.swing.JCheckBox();
        jcbAlcohol = new javax.swing.JCheckBox();
        jcbEnhancer = new javax.swing.JCheckBox();
        jcbGarnishing = new javax.swing.JCheckBox();
        jcbPrimaryJuice = new javax.swing.JCheckBox();
        jcbPreparation = new javax.swing.JCheckBox();
        jcbTaste = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Adaptation Settings");
        setAlwaysOnTop(true);
        setModal(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblStageTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblStageTitle.setText("Adaptation Settings");
        getContentPane().add(lblStageTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 420, 30));

        jLabel8.setText("<html>Please choose the attributes that you wish to be included in the adptation process.</html>");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 410, 30));

        butCurrentReset.setText("Reset");
        butCurrentReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCurrentResetActionPerformed(evt);
            }
        });

        butCurrentAction.setText("Save");
        butCurrentAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCurrentActionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(butCurrentReset, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butCurrentAction, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butCurrentReset)
                    .addComponent(butCurrentAction))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 180, 50));

        jcbSupplementaryJuice.setText("Supplementary Juice");
        jcbSupplementaryJuice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbSupplementaryJuiceActionPerformed(evt);
            }
        });
        getContentPane().add(jcbSupplementaryJuice, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        jcbAlcohol.setSelected(true);
        jcbAlcohol.setText("Alcohol");
        jcbAlcohol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbAlcoholActionPerformed(evt);
            }
        });
        getContentPane().add(jcbAlcohol, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jcbEnhancer.setText("Enhancer");
        jcbEnhancer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbEnhancerActionPerformed(evt);
            }
        });
        getContentPane().add(jcbEnhancer, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jcbGarnishing.setText("Garnishing");
        jcbGarnishing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbGarnishingActionPerformed(evt);
            }
        });
        getContentPane().add(jcbGarnishing, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, -1, -1));

        jcbPrimaryJuice.setSelected(true);
        jcbPrimaryJuice.setText("Primary Juice");
        jcbPrimaryJuice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbPrimaryJuiceActionPerformed(evt);
            }
        });
        getContentPane().add(jcbPrimaryJuice, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));

        jcbPreparation.setText("Preparation");
        jcbPreparation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbPreparationActionPerformed(evt);
            }
        });
        getContentPane().add(jcbPreparation, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jcbTaste.setSelected(true);
        jcbTaste.setText("Taste");
        jcbTaste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTasteActionPerformed(evt);
            }
        });
        getContentPane().add(jcbTaste, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butCurrentActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCurrentActionActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_butCurrentActionActionPerformed

    private void butCurrentResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCurrentResetActionPerformed
        this.jcbAlcohol.setSelected(false);
        this.jcbGarnishing.setSelected(false);
        this.jcbEnhancer.setSelected(false);
        this.jcbPreparation.setSelected(false);
        this.jcbPrimaryJuice.setSelected(false);
        this.jcbSupplementaryJuice.setSelected(false);
        this.jcbTaste.setSelected(false);
    }//GEN-LAST:event_butCurrentResetActionPerformed

    private void jcbSupplementaryJuiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbSupplementaryJuiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbSupplementaryJuiceActionPerformed

    private void jcbAlcoholActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbAlcoholActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbAlcoholActionPerformed

    private void jcbEnhancerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbEnhancerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbEnhancerActionPerformed

    private void jcbGarnishingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbGarnishingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbGarnishingActionPerformed

    private void jcbPrimaryJuiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbPrimaryJuiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbPrimaryJuiceActionPerformed

    private void jcbPreparationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbPreparationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbPreparationActionPerformed

    private void jcbTasteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTasteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbTasteActionPerformed

    public List<String> getAdaptationPreferences() {
        List<String> selected = new ArrayList<>();
        if (this.jcbAlcohol.isSelected() == true) selected.add("ALCOHOL");
        if (this.jcbGarnishing.isSelected() == true) selected.add("GARNISHING");
        if (this.jcbEnhancer.isSelected() == true) selected.add("ENHANCER");
        if (this.jcbPreparation.isSelected() == true) selected.add("PREPARATION");
        if (this.jcbPrimaryJuice.isSelected() == true) selected.add("PRIMARY_JUICE");
        if (this.jcbSupplementaryJuice.isSelected() == true) selected.add("SUPPLEMENTARY_JUICE");
        if (this.jcbTaste.isSelected() == true) selected.add("TASTE");
        return selected;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdaptationSettingsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdaptationSettingsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdaptationSettingsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdaptationSettingsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AdaptationSettingsDialog dialog = new AdaptationSettingsDialog(new javax.swing.JFrame());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butCurrentAction;
    private javax.swing.JButton butCurrentReset;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox jcbAlcohol;
    private javax.swing.JCheckBox jcbEnhancer;
    private javax.swing.JCheckBox jcbGarnishing;
    private javax.swing.JCheckBox jcbPreparation;
    private javax.swing.JCheckBox jcbPrimaryJuice;
    private javax.swing.JCheckBox jcbSupplementaryJuice;
    private javax.swing.JCheckBox jcbTaste;
    private javax.swing.JLabel lblStageTitle;
    // End of variables declaration//GEN-END:variables
}
