/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cocktail.ui;

import cocktail.cbr.Alcohol;
import cocktail.cbr.AlcoholStrength;
import cocktail.cbr.AlcoholType;
import cocktail.cbr.CaseDescription;
import cocktail.cbr.CocktailCase;
import cocktail.cbr.Enhancer;
import cocktail.cbr.EnhancerType;
import cocktail.cbr.Garnishing;
import cocktail.cbr.Preparation;
import cocktail.cbr.PrimaryJuice;
import cocktail.cbr.Recipe;
import cocktail.cbr.SupplementaryJuice;
import cocktail.cbr.Taste;
import jcolibri.cbrcore.CBRCase;


/**
 *
 * @author visaac
 */
public class CaseRevisionPanel extends javax.swing.JPanel {

    private CocktailCase cocktailCase = null;
    /**
     * Creates new form CaseRevisionPanel
     */
    public CaseRevisionPanel(CocktailCase cocktailCase) {
        this.cocktailCase = cocktailCase;
        initComponents();
        populateSelectors();
        populateCase();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jcbAlcoholType = new javax.swing.JComboBox<>();
        jcbEnhancerType = new javax.swing.JComboBox<>();
        jcbPrimaryJuice = new javax.swing.JComboBox<>();
        jcbSupplementaryJuice = new javax.swing.JComboBox<>();
        jcbGarnishing = new javax.swing.JComboBox<>();
        jcbTaste = new javax.swing.JComboBox<>();
        jcbPreparation = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtRecipeTitle = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jcbAlcoholStrength = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jcbAlcohol = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jcbEnhancer = new javax.swing.JComboBox<>();
        jchkRetain = new javax.swing.JCheckBox();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Alcohol Type");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 38, -1, -1));

        jLabel2.setText("Primary Juice");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 90, 118, -1));

        jLabel3.setText("Supplementary Juice");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 116, 118, -1));

        jLabel4.setText("Garnishing");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 142, 118, -1));

        jLabel5.setText("Enhancer Type");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 64, 118, -1));

        jLabel6.setText("Taste Preference");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 168, 118, -1));

        jLabel7.setText("Preparation Method");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 194, 118, -1));

        jPanel1.add(jcbAlcoholType, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 35, 235, -1));

        jPanel1.add(jcbEnhancerType, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 61, 235, -1));

        jPanel1.add(jcbPrimaryJuice, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 87, 235, -1));

        jPanel1.add(jcbSupplementaryJuice, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 113, 235, -1));

        jPanel1.add(jcbGarnishing, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 139, 235, -1));

        jPanel1.add(jcbTaste, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 165, 235, -1));

        jPanel1.add(jcbPreparation, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 191, 235, -1));

        jLabel9.setText("Recipe Title");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 14, -1, -1));
        jPanel1.add(txtRecipeTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 11, 235, -1));

        jLabel10.setText("Alcohol Strength");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 220, -1, -1));

        jPanel1.add(jcbAlcoholStrength, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 217, 235, -1));

        jLabel11.setText("Alcohol");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 246, -1, -1));

        jPanel1.add(jcbAlcohol, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 243, 235, -1));

        jLabel12.setText("Enhancer");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 272, -1, -1));

        jPanel1.add(jcbEnhancer, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 269, 235, -1));

        jchkRetain.setText("Retain");
        jchkRetain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkRetainActionPerformed(evt);
            }
        });
        jPanel1.add(jchkRetain, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 310));
    }// </editor-fold>//GEN-END:initComponents

    private void jchkRetainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkRetainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jchkRetainActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jcbAlcohol;
    private javax.swing.JComboBox<String> jcbAlcoholStrength;
    private javax.swing.JComboBox<String> jcbAlcoholType;
    private javax.swing.JComboBox<String> jcbEnhancer;
    private javax.swing.JComboBox<String> jcbEnhancerType;
    private javax.swing.JComboBox<String> jcbGarnishing;
    private javax.swing.JComboBox<String> jcbPreparation;
    private javax.swing.JComboBox<String> jcbPrimaryJuice;
    private javax.swing.JComboBox<String> jcbSupplementaryJuice;
    private javax.swing.JComboBox<String> jcbTaste;
    private javax.swing.JCheckBox jchkRetain;
    private javax.swing.JTextField txtRecipeTitle;
    // End of variables declaration//GEN-END:variables
    private void populateSelectors() {
        for (AlcoholType e : AlcoholType.values()) {
            jcbAlcoholType.addItem(e.toString());
        }
        
        for (EnhancerType e : EnhancerType.values()) {
            jcbEnhancerType.addItem(e.toString());
        }
        
        for (PrimaryJuice e : PrimaryJuice.values()) {
            jcbPrimaryJuice.addItem(e.toString());
        }
        
        for (SupplementaryJuice e : SupplementaryJuice.values()) {
            jcbSupplementaryJuice.addItem(e.toString());
        }
        
        for (Taste e : Taste.values()) {
            jcbTaste.addItem(e.toString());
        }
        
        for (Garnishing e : Garnishing.values()) {
            jcbGarnishing.addItem(e.toString());
        }
        
        for (Preparation e : Preparation.values()) {
            jcbPreparation.addItem(e.toString());
        }        

        for (Alcohol e : Alcohol.values()) {
            jcbAlcohol.addItem(e.toString());
        }        
        
        for (AlcoholStrength e : AlcoholStrength.values()) {
            jcbAlcoholStrength.addItem(e.toString());
        }

        for (Enhancer e : Enhancer.values()) {
            jcbEnhancer.addItem(e.toString());
        }        
                
        
    }

    private void populateCase() {
        jcbAlcoholType.setSelectedItem(cocktailCase.description.getAlcoholType().toString());
        jcbEnhancerType.setSelectedItem(cocktailCase.description.getEnhancerType().toString());
        jcbGarnishing.setSelectedItem(cocktailCase.description.getGarnishing().toString());
        jcbPreparation.setSelectedItem(cocktailCase.description.getPreparation().toString());
        jcbPrimaryJuice.setSelectedItem(cocktailCase.description.getPrimaryJuice().toString());
        jcbSupplementaryJuice.setSelectedItem(cocktailCase.description.getSupplementaryJuice().toString());
        jcbTaste.setSelectedItem(cocktailCase.description.getTaste().toString());
        txtRecipeTitle.setText(cocktailCase.recipe.getRecipeName().replace("_", " "));
        jcbAlcohol.setSelectedItem(cocktailCase.recipe.getAlcohol().toString());
        jcbAlcoholStrength.setSelectedItem(cocktailCase.recipe.getAlcoholStrength().toString());
        jcbEnhancer.setSelectedItem(cocktailCase.recipe.getEnhancer().toString());
        
    }
    
    public CBRCase getCaseForRetension() {
        if (jchkRetain.isSelected() == false) {
            return null;
        } 
        
        CBRCase _case = new CBRCase();

        CaseDescription desc = new CaseDescription();
        desc.setAlcoholType(AlcoholType.valueOf(jcbAlcoholType.getSelectedItem().toString()));
        desc.setEnhancerType(EnhancerType.valueOf(jcbEnhancerType.getSelectedItem().toString()));
        desc.setGarnishing(Garnishing.valueOf(jcbGarnishing.getSelectedItem().toString()));
        desc.setPreparation(Preparation.valueOf(jcbPreparation.getSelectedItem().toString()));
        desc.setPrimaryJuice(PrimaryJuice.valueOf(jcbPrimaryJuice.getSelectedItem().toString()));
        desc.setSupplementaryJuice(SupplementaryJuice.valueOf(jcbSupplementaryJuice.getSelectedItem().toString()));
        desc.setTaste(Taste.valueOf(jcbTaste.getSelectedItem().toString()));
        
        Recipe recipe = new Recipe();
        recipe.setAlcohol(Alcohol.valueOf(jcbAlcohol.getSelectedItem().toString()));
        recipe.setAlcoholStrength(AlcoholStrength.valueOf(jcbAlcoholStrength.getSelectedItem().toString()));
        recipe.setEnhancer(Enhancer.valueOf(jcbEnhancer.getSelectedItem().toString()));
        recipe.setRecipeName(txtRecipeTitle.getText());
        
        _case.setDescription(desc);
        _case.setSolution(recipe);
        return _case;
    }
}
