/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cocktail.ui;

import java.awt.BorderLayout;
import java.awt.Container;
import javax.swing.DefaultListModel;
import javax.swing.JComponent;

/**
 *
 * @author visaac
 */
public class ImportanceConfigPanel extends javax.swing.JPanel {

    /**
     * Creates new form QueryPanel
     */
    public ImportanceConfigPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        jSlider2 = new javax.swing.JSlider();
        jSlider3 = new javax.swing.JSlider();
        jSlider4 = new javax.swing.JSlider();
        jSlider5 = new javax.swing.JSlider();
        jSlider6 = new javax.swing.JSlider();
        jSlider7 = new javax.swing.JSlider();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Alcohol");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 41, 150, 35));

        jLabel2.setText("Primary Juice");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 150, 35));

        jLabel3.setText("Supplementary Juice");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 150, 35));

        jLabel4.setText("Garnishing");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 150, 35));

        jLabel5.setText("Enhancer");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 150, 35));

        jLabel6.setText("Taste Preference");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 150, 35));

        jLabel7.setText("Preparation Method");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 150, 35));

        jLabel8.setText("<html>Please use the sliders to choose the importance of each option. By default, all options will be given equal importance. Your selection here will also determine what customizations will be done to the recipies found later on.</html>");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 445, -1));
        add(jSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 293, -1));
        add(jSlider2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 293, -1));
        add(jSlider3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 293, -1));
        add(jSlider4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 293, -1));
        add(jSlider5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 293, -1));
        add(jSlider6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 293, -1));
        add(jSlider7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 293, -1));
    }// </editor-fold>//GEN-END:initComponents
    private DefaultListModel<String> blackListedModel = new DefaultListModel<>();
    private DefaultListModel<String> whiteListedModel = new DefaultListModel<>();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSlider jSlider2;
    private javax.swing.JSlider jSlider3;
    private javax.swing.JSlider jSlider4;
    private javax.swing.JSlider jSlider5;
    private javax.swing.JSlider jSlider6;
    private javax.swing.JSlider jSlider7;
    // End of variables declaration//GEN-END:variables
}
