/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cocktail.ui;

import cocktail.cbr.CocktailCase;
import java.awt.BorderLayout;
import java.awt.Container;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JComponent;
import javax.swing.JScrollPane;
import jcolibri.cbrcore.CBRCase;
import jcolibri.method.retrieve.RetrievalResult;

/**
 *
 * @author visaac
 */
public class OutcomePanel extends javax.swing.JPanel {

    private List<CaseRevisionPanel> casePanes = new ArrayList<>();
    /**
     * Creates new form QueryPanel
     */
    public OutcomePanel() {
        initComponents();
    }

    public void populateCases(List<CocktailCase> cases) {
        jTabbedPane1.removeAll();
        casePanes.clear();
        for (int i = 0 ; i < cases.size() ; i++ ) {
            CaseRevisionPanel crp = new CaseRevisionPanel(cases.get(i));
            casePanes.add(crp);
            jTabbedPane1.addTab(String.valueOf(i), crp);
        }
    }
    
    public List<CBRCase> getCasesToRetain() {
        List<CBRCase> casesToRetain = new ArrayList<>();

        for (CaseRevisionPanel crp : casePanes) {
            CBRCase caseForRetension = crp.getCaseForRetension();
            if (caseForRetension != null) {
                casesToRetain.add(caseForRetension);
            }
        }
        
        return casesToRetain;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setText("<html>Please click on the settings options to customize your adaptation parameters and click on the refresh button below.</html>");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 490, -1));

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 490, 350));
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

    void reset() {
        jTabbedPane1.removeAll();
    }
}
