/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools - Templates
 * and open the template in the editor.
 */
package cocktail.ui;

import cocktail.cbr.AlcoholType;
import cocktail.cbr.EnhancerType;
import cocktail.cbr.Garnishing;
import cocktail.cbr.PrimaryJuice;
import cocktail.cbr.SupplementaryJuice;
import cocktail.cbr.Taste;
import cocktail.cbr.Preparation;
import java.awt.BorderLayout;
import java.awt.Container;
import java.util.HashMap;
import java.util.Map;
import javax.swing.DefaultListModel;
import javax.swing.JComponent;

/**
 *
 * @author visaac
 */
public class SearchPanel extends javax.swing.JPanel {

    private Map<Filter, String> chosenFiltersAndValues = new HashMap<>();
    /**
     * Creates new form QueryPanel
     */
    public SearchPanel() {
        initComponents();
        populateSelectors();
    }

    public Map<Filter, String>  getFilters() {
        if (jcbAlcoholType.getSelectedIndex() != -1) {
            chosenFiltersAndValues.put(Filter.AlcoholType, jcbAlcoholType.getSelectedItem().toString() + "-" + jcbAvoidAlcohol.isSelected());
        }
        
        if (jcbEnhancerType.getSelectedIndex() != -1) {
            chosenFiltersAndValues.put(Filter.EnhancerType, jcbEnhancerType.getSelectedItem().toString() + "-" + jcbAvoidEnhancer.isSelected());
        }
        
        if (jcbPrimaryJuice.getSelectedIndex() != -1) {
            chosenFiltersAndValues.put(Filter.PrimaryJuice, jcbPrimaryJuice.getSelectedItem().toString()+ "-" + jcbAvoidPrimaryJuice.isSelected());
        }
        
        if (jcbSupplementaryJuice.getSelectedIndex() != -1) {
            chosenFiltersAndValues.put(Filter.SupplementaryJuice, jcbSupplementaryJuice.getSelectedItem().toString()+ "-" + jcbAvoidSupplementaryJuice.isSelected());
        }
        
        if (jcbGarnishing.getSelectedIndex() != -1) {
            chosenFiltersAndValues.put(Filter.Garnishing, jcbGarnishing.getSelectedItem().toString()+ "-" + jcbAvoidGarnishing.isSelected());
        }
        
        if (jcbPreparation.getSelectedIndex() != -1) {
            chosenFiltersAndValues.put(Filter.Preparation, jcbPreparation.getSelectedItem().toString()+ "-" + jcbAvoidPreparation.isSelected());
        }
        
        if (jcbTaste.getSelectedIndex() != -1) {
            chosenFiltersAndValues.put(Filter.Taste, jcbTaste.getSelectedItem().toString()+ "-" + jcbAvoidTaste.isSelected());
        }
        
        System.out.println("chosenFiltersAndValues "  + chosenFiltersAndValues);
        return chosenFiltersAndValues;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jcbAvoidPrimaryJuice = new javax.swing.JCheckBox();
        jcbAvoidAlcohol = new javax.swing.JCheckBox();
        jcbAvoidSupplementaryJuice = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jcbAvoidGarnishing = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jcbAvoidEnhancer = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jcbAvoidTaste = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jcbAvoidPreparation = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jcbAlcoholType = new javax.swing.JComboBox<>();
        jcbEnhancerType = new javax.swing.JComboBox<>();
        jcbPrimaryJuice = new javax.swing.JComboBox<>();
        jcbSupplementaryJuice = new javax.swing.JComboBox<>();
        jcbGarnishing = new javax.swing.JComboBox<>();
        jcbTaste = new javax.swing.JComboBox<>();
        jcbPreparation = new javax.swing.JComboBox<>();

        jLabel1.setText("Alcohol Type");

        jLabel2.setText("Primary Juice");

        jLabel3.setText("Supplementary Juice");

        jcbAvoidPrimaryJuice.setText("Avoid");
        jcbAvoidPrimaryJuice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbAvoidPrimaryJuiceActionPerformed(evt);
            }
        });

        jcbAvoidAlcohol.setText("Avoid");
        jcbAvoidAlcohol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbAvoidAlcoholActionPerformed(evt);
            }
        });

        jcbAvoidSupplementaryJuice.setText("Avoid");
        jcbAvoidSupplementaryJuice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbAvoidSupplementaryJuiceActionPerformed(evt);
            }
        });

        jLabel4.setText("Garnishing");

        jcbAvoidGarnishing.setText("Avoid");
        jcbAvoidGarnishing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbAvoidGarnishingActionPerformed(evt);
            }
        });

        jLabel5.setText("Enhancer Type");

        jcbAvoidEnhancer.setText("Avoid");
        jcbAvoidEnhancer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbAvoidEnhancerActionPerformed(evt);
            }
        });

        jLabel6.setText("Taste Preference");

        jcbAvoidTaste.setText("Avoid");
        jcbAvoidTaste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbAvoidTasteActionPerformed(evt);
            }
        });

        jLabel7.setText("Preparation Method");

        jcbAvoidPreparation.setText("Avoid");
        jcbAvoidPreparation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbAvoidPreparationActionPerformed(evt);
            }
        });

        jLabel8.setText("<html>Please click on the buttons against each option to choose your preference. <br>Use the check box to avoid the chosen preference. <br>You can click the options again to change your preference.</html>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcbPreparation, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcbEnhancerType, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcbAlcoholType, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcbPrimaryJuice, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcbSupplementaryJuice, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcbGarnishing, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcbTaste, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbAvoidPreparation)
                            .addComponent(jcbAvoidTaste)
                            .addComponent(jcbAvoidGarnishing)
                            .addComponent(jcbAvoidSupplementaryJuice)
                            .addComponent(jcbAvoidPrimaryJuice)
                            .addComponent(jcbAvoidEnhancer)
                            .addComponent(jcbAvoidAlcohol))
                        .addGap(50, 50, 50))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jcbAvoidAlcohol)
                    .addComponent(jcbAlcoholType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jcbAvoidEnhancer)
                    .addComponent(jcbEnhancerType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcbAvoidPrimaryJuice)
                    .addComponent(jcbPrimaryJuice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jcbAvoidSupplementaryJuice)
                    .addComponent(jcbSupplementaryJuice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jcbAvoidGarnishing)
                    .addComponent(jcbGarnishing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jcbAvoidTaste)
                    .addComponent(jcbTaste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jcbPreparation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbAvoidPreparation))
                .addGap(19, 19, 19)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jcbAvoidPrimaryJuiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbAvoidPrimaryJuiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbAvoidPrimaryJuiceActionPerformed

    private void jcbAvoidAlcoholActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbAvoidAlcoholActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbAvoidAlcoholActionPerformed

    private void jcbAvoidSupplementaryJuiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbAvoidSupplementaryJuiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbAvoidSupplementaryJuiceActionPerformed

    private void jcbAvoidGarnishingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbAvoidGarnishingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbAvoidGarnishingActionPerformed

    private void jcbAvoidEnhancerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbAvoidEnhancerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbAvoidEnhancerActionPerformed

    private void jcbAvoidTasteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbAvoidTasteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbAvoidTasteActionPerformed

    private void jcbAvoidPreparationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbAvoidPreparationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbAvoidPreparationActionPerformed
    private DefaultListModel<String> blackListedModel = new DefaultListModel<>();
    private DefaultListModel<String> whiteListedModel = new DefaultListModel<>();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JComboBox<String> jcbAlcoholType;
    private javax.swing.JCheckBox jcbAvoidAlcohol;
    private javax.swing.JCheckBox jcbAvoidEnhancer;
    private javax.swing.JCheckBox jcbAvoidGarnishing;
    private javax.swing.JCheckBox jcbAvoidPreparation;
    private javax.swing.JCheckBox jcbAvoidPrimaryJuice;
    private javax.swing.JCheckBox jcbAvoidSupplementaryJuice;
    private javax.swing.JCheckBox jcbAvoidTaste;
    private javax.swing.JComboBox<String> jcbEnhancerType;
    private javax.swing.JComboBox<String> jcbGarnishing;
    private javax.swing.JComboBox<String> jcbPreparation;
    private javax.swing.JComboBox<String> jcbPrimaryJuice;
    private javax.swing.JComboBox<String> jcbSupplementaryJuice;
    private javax.swing.JComboBox<String> jcbTaste;
    // End of variables declaration//GEN-END:variables

    void resetSelections() {
        chosenFiltersAndValues.clear();
        jcbAlcoholType.setSelectedIndex(0);
        jcbEnhancerType.setSelectedIndex(0);
        jcbPrimaryJuice.setSelectedIndex(0);
        jcbSupplementaryJuice.setSelectedIndex(0);
        jcbGarnishing.setSelectedIndex(0);
        jcbPreparation.setSelectedIndex(0);
        jcbTaste.setSelectedIndex(0);

        jcbAvoidAlcohol.setSelected(false);
        jcbAvoidEnhancer.setSelected(false);
        jcbAvoidGarnishing.setSelected(false);
        jcbAvoidPreparation.setSelected(false);
        jcbAvoidPrimaryJuice.setSelected(false);
        jcbAvoidSupplementaryJuice.setSelected(false);
        jcbAvoidTaste.setSelected(false);
    }

    private void populateSelectors() {
        for (AlcoholType e : AlcoholType.values()) {
            jcbAlcoholType.addItem(e.toString());
        }
        
        for (EnhancerType e : EnhancerType.values()) {
            jcbEnhancerType.addItem(e.toString());
        }
        
        for (PrimaryJuice e : PrimaryJuice.values()) {
            jcbPrimaryJuice.addItem(e.toString());
        }
        
        for (SupplementaryJuice e : SupplementaryJuice.values()) {
            jcbSupplementaryJuice.addItem(e.toString());
        }
        
        for (Taste e : Taste.values()) {
            jcbTaste.addItem(e.toString());
        }
        
        for (Garnishing e : Garnishing.values()) {
            jcbGarnishing.addItem(e.toString());
        }
        
        for (Preparation e : Preparation.values()) {
            jcbPreparation.addItem(e.toString());
        }        
    }
}
